sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hike327/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hike327/docker-react npm run test

